-- MySQL Script generated by MySQL Workbench
-- Tue Dec  1 13:21:02 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spen7755
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spen7755
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spen7755` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `spen7755` ;

-- -----------------------------------------------------
-- Table `spen7755`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spen7755`.`customers` ;

CREATE TABLE IF NOT EXISTS `spen7755`.`customers` (
  `custID` INT NOT NULL AUTO_INCREMENT,
  `custFName` VARCHAR(30) NOT NULL,
  `custLName` VARCHAR(30) NOT NULL,
  `custAddress` VARCHAR(30) NOT NULL,
  `custCity` VARCHAR(30) NOT NULL,
  `custState` VARCHAR(30) NOT NULL,
  `custZip` CHAR(10) NOT NULL,
  `custPhone` CHAR(20) NOT NULL,
  PRIMARY KEY (`custID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spen7755`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spen7755`.`orders` ;

CREATE TABLE IF NOT EXISTS `spen7755`.`orders` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `dateTimePlaced` DATETIME NOT NULL,
  `custID` INT NOT NULL,
  `pizzaDesc` VARCHAR(255) NOT NULL,
  `priceSub` FLOAT NOT NULL,
  `tax` FLOAT NOT NULL,
  `priceTotal` FLOAT NOT NULL,
  `completed` CHAR(1) NOT NULL DEFAULT 'n',
  PRIMARY KEY (`orderID`),
  CONSTRAINT `custID_FK`
    FOREIGN KEY (`custID`)
    REFERENCES `spen7755`.`customers` (`custID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `custID_FK_idx` ON `spen7755`.`orders` (`custID` ASC);


-- -----------------------------------------------------
-- Table `spen7755`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spen7755`.`admins` ;

CREATE TABLE IF NOT EXISTS `spen7755`.`admins` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(25) NOT NULL,
  `firstName` VARCHAR(25) NOT NULL,
  `lastName` VARCHAR(25) NOT NULL,
  `password` VARCHAR(300) NOT NULL,
  `adminLevel` INT NOT NULL DEFAULT 2,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
